name: cppcheck-action
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Install cppcheck
        run: sudo apt-get -y install cppcheck
      - name: Cppcheck code
        run: cppcheck LTTS_C_Miniproject_260904/3_Implementation







[![Contribution Check - Git Inspector](https://github.com/Lahari-1999/LTTS_C_Miniproject_260904/actions/workflows/Gitinspector.yml/badge.svg)](https://github.com/Lahari-1999/LTTS_C_Miniproject_260904/actions/workflows/Gitinspector.yml)



[![Static Code Quality- Cppcheck](https://github.com/Lahari-1999/LTTS_C_Miniproject_260904/actions/workflows/cpp.yml/badge.svg)](https://github.com/Lahari-1999/LTTS_C_Miniproject_260904/actions/workflows/cpp.yml)
 

