  
name: Static Code Quality- Cppcheck

on:
  push:
    branches: [ main ]
  

jobs:
  cppcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cppcheck
      run: sudo apt -y install cppcheck
    - name: Run cppcheck
      run: cppcheck LTTS_C_Miniproject_260904/3_Implementation
